languageCode = "en"
languageName = "English"
weight = 1
title = "Khalil Chettaoui"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
#  logo = "img/necromancer.png"
  description = "Linux | Kubernetes | Go"

[params.author]
  name = "Khalil Chettaoui"
  email = "khalil.che26@gmail.com"
  image = "img/me.jpg"
  headline = "Linux | Kubernetes | Go"
  bio = "Hello 👋, I do Software Development and DevOps." 
  links = [
    {github = "https://github.com/kubemancer"},
    {mastodon = "https://infosec.exchange/@necromancer26"},
    {bluesky="https://bsky.app/profile/khalilchettaoui.space"},
    {linkedin = "https://www.linkedin.com/in/khalil-ch"},
    {email="mailto:contact@khalilchettaoui.space"}
  ]
